apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product

  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: gabosarmiento/micro-service-product
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30080
  selector:
    app: product